import { Translations, Language } from './types';

export const LOCALES: Translations = {
  [Language.EN]: {
    'app_title': 'Skyon App',
    'nav_home': 'Home',
    'nav_market': 'Market',
    'nav_services': 'Services',
    'nav_bazaar': 'Bazaar',
    'nav_events': 'Events',
    'nav_medical': 'Medical',
    'nav_transport': 'Transport',
    'nav_parking': 'Parking Watch',
    'nav_profile': 'Profile',
    'home_welcome': 'Welcome to SKYON',
    'market_title': 'Community Marketplace',
    'market_post_item': 'Post an Item',
    'bazaar_title': 'Community Bazaar',
    'bazaar_subtitle': 'Discover stores from your neighbors',
    'bazaar_add_store': 'Add Your Store',
    'services_title': 'Approved Vendors',
    'services_search_placeholder': 'Search for a service...',
    'listing_condition': 'Condition',
    'listing_price': 'Price',
    'listing_contact_seller': 'Contact Seller',
    'listing_similar': 'Similar Listings',
    'listing_make_offer': 'Make Offer',
    'listing_type': 'Listing Type',
    'vendor_book_service': 'Book Service',
    'vendor_reviews': 'Reviews',
    'store_products': 'Products',
    'contact_owner': 'Contact Owner',
    'chat_on_whatsapp': 'Chat on WhatsApp',
    'call_owner': 'Call Owner',
    'back_to_bazaar': 'Back to Bazaar',
    'form_title': 'Title',
    'form_description': 'Description',
    'form_category': 'Category',
    'form_price': 'Price (INR)',
    'form_condition': 'Condition',
    'form_add_photo': 'Add Photo',
    'form_post_listing': 'Post Listing',
    'form_ai_suggestion': 'AI Suggestion:',
    'form_add_store_title': 'Add Your Business to the Bazaar',
    'form_store_name': 'Store Name',
    'form_owner_name': 'Your Name',
    'form_whatsapp_number': 'WhatsApp Number',
    'form_phone_number': 'Phone Number (for calls)',
    'form_submit_store': 'Submit for Approval',
    'form_vehicle_number': 'Vehicle Number',
    'form_location': 'Parking Slot / Location',
    'free': 'Free',
    'language': 'Language',
    'events_title': 'Community Events',
    'events_rsvp': 'RSVP',
    'events_people_going': 'people going',
    'lost_and_found_title': 'Lost & Found',
    'lost_and_found_report_item': 'Report Item',
    'lost_and_found_status_lost': 'Lost',
    'lost_and_found_status_found': 'Found',
    'filter_by': 'Filter by',
    'filter_all': 'All',
    'filter_for_sale': 'For Sale',
    'filter_for_rent': 'For Rent',
    'emergency_contacts': 'Emergency Contacts',
    'lost_found': 'Lost & Found',
    'medical_title': 'Medical & Health Hub',
    'medical_hospitals_clinics': 'Nearby Hospitals & Clinics',
    'medical_find_doctor': 'Find a Doctor',
    'medical_resident_doctors': 'Resident Doctors',
    'medical_first_aid': 'Request First Aid',
    'transport_title': 'Transport & Carpooling',
    'transport_carpool_board': 'Carpool Board',
    'transport_driver_requests': 'Driver/Ride Requests',
    'transport_post_ride': 'Post a Ride',
    'transport_post_request': 'Post Request',
    'parking_title': 'Parking Violations',
    'parking_report_violation': 'Report Violation',
    'todays_dishes_title': "Today's Homemade Food",
    'post_todays_dish': "Post Today's Dish",
    'todays_dishes_subtitle': 'Freshly made by your neighbors, just for today!',
    'use_template': 'Use a Template',
    'dish_name': 'Dish Name',
    'price': 'Price',
    'post_dish': 'Post Dish',
    'latest_dishes': 'Latest Dishes',
    'auth_login': 'Login',
    'auth_logout': 'Logout',
    'auth_login_with_google': 'Sign in with Google',
    'auth_please_login': 'Please log in to continue',
    'profile_title': 'My Profile',
    'profile_setup_title': 'Complete Your Profile',
    'profile_setup_subtitle': 'Please provide your details to access all community features.',
    'profile_name': 'Your Name',
    'profile_block': 'Block',
    'profile_flat_number': 'Flat Number',
    'profile_save': 'Save Profile',
    'profile_saved_success': 'Profile saved successfully!',
  },
  [Language.HI]: {
    'app_title': 'स्कायन ऐप',
    'nav_home': 'होम',
    'nav_market': 'बाजार',
    'nav_services': 'सेवाएं',
    'nav_bazaar': 'बाज़ार',
    'nav_events': 'इवेंट्स',
    'nav_medical': 'मेडिकल',
    'nav_transport': 'परिवहन',
    'nav_parking': 'पार्किंग वॉच',
    'nav_profile': 'प्रोफ़ाइल',
    'home_welcome': 'स्कायन में आपका स्वागत है',
    'market_title': 'सामुदायिक बाज़ार',
    'market_post_item': 'एक आइटम पोस्ट करें',
    'bazaar_title': 'सामुदायिक बाज़ार',
    'bazaar_subtitle': 'अपने पड़ोसियों की दुकानें खोजें',
    'bazaar_add_store': 'अपनी दुकान जोड़ें',
    'services_title': 'अनुमोदित विक्रेता',
    'services_search_placeholder': 'किसी सेवा की खोज करें...',
    'listing_condition': 'स्थिति',
    'listing_price': 'कीमत',
    'listing_contact_seller': 'विक्रेता से संपर्क करें',
    'listing_similar': 'समान लिस्टिंग',
    'listing_make_offer': 'प्रस्ताव करें',
    'listing_type': 'लिस्टिंग का प्रकार',
    'vendor_book_service': 'सेवा बुक करें',
    'vendor_reviews': 'समीक्षाएं',
    'store_products': 'उत्पाद',
    'contact_owner': 'मालिक से संपर्क करें',
    'chat_on_whatsapp': 'व्हाट्सएप पर चैट करें',
    'call_owner': 'मालिक को कॉल करें',
    'back_to_bazaar': 'बाजार वापस जाएं',
    'form_title': 'शीर्षक',
    'form_description': 'विवरण',
    'form_category': 'श्रेणी',
    'form_price': 'मूल्य (INR)',
    'form_condition': 'स्थिति',
    'form_add_photo': 'फोटो जोड़ें',
    'form_post_listing': 'लिस्टिंग पोस्ट करें',
    'form_ai_suggestion': 'एआई सुझाव:',
    'form_add_store_title': 'अपना व्यवसाय बाज़ार में जोड़ें',
    'form_store_name': 'स्टोर का नाम',
    'form_owner_name': 'आपका नाम',
    'form_whatsapp_number': 'व्हाट्सएप नंबर',
    'form_phone_number': 'फ़ोन नंबर (कॉल के लिए)',
    'form_submit_store': 'अनुमोदन के लिए सबमिट करें',
    'form_vehicle_number': 'गाडी नंबर',
    'form_location': 'पार्किंग स्लॉट / स्थान',
    'free': 'मुफ़्त',
    'language': 'भाषा',
    'events_title': 'सामुदायिक इवेंट्स',
    'events_rsvp': 'आरएसवीपी',
    'events_people_going': 'लोग जा रहे हैं',
    'lost_and_found_title': 'खोया और पाया',
    'lost_and_found_report_item': 'आइटम रिपोर्ट करें',
    'lost_and_found_status_lost': 'खोया',
    'lost_and_found_status_found': 'पाया',
    'filter_by': 'फ़िल्टर करें',
    'filter_all': 'सभी',
    'filter_for_sale': 'बिक्री के लिए',
    'filter_for_rent': 'किराए के लिए',
    'emergency_contacts': 'आपातकालीन संपर्क',
    'lost_found': 'खोया पाया',
    'medical_title': 'मेडिकल और हेल्थ हब',
    'medical_hospitals_clinics': 'आस-पास के अस्पताल और क्लीनिक',
    'medical_find_doctor': 'डॉक्टर खोजें',
    'medical_resident_doctors': 'निवासी डॉक्टर',
    'medical_first_aid': 'प्राथमिक उपचार का अनुरोध करें',
    'transport_title': 'परिवहन और कारपूलिंग',
    'transport_carpool_board': 'कारपूल बोर्ड',
    'transport_driver_requests': 'ड्राइवर/राइड अनुरोध',
    'transport_post_ride': 'एक राइड पोस्ट करें',
    'transport_post_request': 'अनुरोध पोस्ट करें',
    'parking_title': 'पार्किंग उल्लंघन',
    'parking_report_violation': 'उल्लंघन की रिपोर्ट करें',
    'todays_dishes_title': 'आज के घर के बने व्यंजन',
    'post_todays_dish': 'आज की डिश पोस्ट करें',
    'todays_dishes_subtitle': 'आपके पड़ोसियों द्वारा ताज़ा बनाया गया, सिर्फ आज के लिए!',
    'use_template': 'एक टेम्पलेट का प्रयोग करें',
    'dish_name': 'डिश का नाम',
    'price': 'कीमत',
    'post_dish': 'डिश पोस्ट करें',
    'latest_dishes': 'नवीनतम व्यंजन',
    'auth_login': 'लॉग इन करें',
    'auth_logout': 'लॉग आउट करें',
    'auth_login_with_google': 'Google से साइन इन करें',
    'auth_please_login': 'जारी रखने के लिए कृपया लॉग इन करें',
    'profile_title': 'मेरी प्रोफ़ाइल',
    'profile_setup_title': 'अपनी प्रोफ़ाइल पूरी करें',
    'profile_setup_subtitle': 'सभी सामुदायिक सुविधाओं तक पहुंचने के लिए कृपया अपना विवरण प्रदान करें।',
    'profile_name': 'आपका नाम',
    'profile_block': 'ब्लॉक',
    'profile_flat_number': 'फ्लैट नंबर',
    'profile_save': 'प्रोफ़ाइल सहेजें',
    'profile_saved_success': 'प्रोफ़ाइल सफलतापूर्वक सहेजी गई!',
  },
  [Language.TE]: {
    'app_title': 'స్కైయాన్ యాప్',
    'nav_home': 'హోమ్',
    'nav_market': 'మార్కెట్',
    'nav_services': 'సేవలు',
    'nav_bazaar': 'బజార్',
    'nav_events': 'ఈవెంట్‌లు',
    'nav_medical': 'వైద్యం',
    'nav_transport': 'రవాణా',
    'nav_parking': 'పార్కింగ్ వాచ్',
    'nav_profile': 'ప్రొఫైల్',
    'home_welcome': 'స్కైయాన్‌కు స్వాగతం',
    'market_title': 'కమ్యూనిటీ మార్కెట్‌ప్లేస్',
    'market_post_item': 'వస్తువును పోస్ట్ చేయండి',
    'bazaar_title': 'కమ్యూనిటీ బజార్',
    'bazaar_subtitle': 'మీ పొరుగువారి నుండి దుకాణాలను కనుగొనండి',
    'bazaar_add_store': 'మీ స్టోర్‌ను జోడించండి',
    'services_title': 'ఆమోదించబడిన విక్రేతలు',
    'services_search_placeholder': 'ఒక సేవ కోసం శోధించండి...',
    'listing_condition': 'పరిస్థితి',
    'listing_price': 'ధర',
    'listing_contact_seller': 'అమ్మకందారుని సంప్రదించండి',
    'listing_similar': 'ఇలాంటి జాబితాలు',
    'listing_make_offer': 'ఆఫర్ చేయండి',
    'listing_type': 'జాబితా రకం',
    'vendor_book_service': 'సేవను బుక్ చేయండి',
    'vendor_reviews': 'సమీక్షలు',
    'store_products': 'ఉత్పత్తులు',
    'contact_owner': 'యజమానిని సంప్రదించండి',
    'chat_on_whatsapp': 'వాట్సాప్‌లో చాట్ చేయండి',
    'call_owner': 'యజమానికి కాల్ చేయండి',
    'back_to_bazaar': 'బజార్‌కు తిరిగి వెళ్లండి',
    'form_title': 'శీర్షిక',
    'form_description': 'వివరణ',
    'form_category': 'వర్గం',
    'form_price': 'ధర (INR)',
    'form_condition': 'పరిస్థితి',
    'form_add_photo': 'ఫోటో జోడించండి',
    'form_post_listing': 'జాబితాను పోస్ట్ చేయండి',
    'form_ai_suggestion': 'AI సూచన:',
    'form_add_store_title': 'మీ వ్యాపారాన్ని బజార్‌లో జోడించండి',
    'form_store_name': 'స్టోర్ పేరు',
    'form_owner_name': 'మీ పేరు',
    'form_whatsapp_number': 'వాట్సాప్ నంబర్',
    'form_phone_number': 'ఫోన్ నంబర్ (కాల్స్ కోసం)',
    'form_submit_store': 'ఆమోదం కోసం సమర్పించండి',
    'form_vehicle_number': 'వాహనం నంబర్',
    'form_location': 'పార్కింగ్ స్లాట్ / ప్రదేశం',
    'free': 'ఉచితం',
    'language': 'భాష',
    'events_title': 'కమ్యూనిటీ ఈవెంట్‌లు',
    'events_rsvp': 'RSVP',
    'events_people_going': 'మంది వెళ్తున్నారు',
    'lost_and_found_title': 'పోయినవి మరియు దొరికినవి',
    'lost_and_found_report_item': 'వస్తువును నివేదించండి',
    'lost_and_found_status_lost': 'పోయింది',
    'lost_and_found_status_found': 'దొరికింది',
    'filter_by': 'ద్వారా ఫిల్టర్ చేయండి',
    'filter_all': 'అన్నీ',
    'filter_for_sale': 'అమ్మకానికి',
    'filter_for_rent': 'అద్దెకు',
    'emergency_contacts': 'అత్యవసర సంప్రదింపులు',
    'lost_found': 'పోయినవి-దొరికినవి',
    'medical_title': 'వైద్య & ఆరోగ్య కేంద్రం',
    'medical_hospitals_clinics': 'సమీపంలోని ఆసుపత్రులు & క్లినిక్‌లు',
    'medical_find_doctor': 'డాక్టర్‌ను కనుగొనండి',
    'medical_resident_doctors': 'నివాస వైద్యులు',
    'medical_first_aid': 'ప్రథమ చికిత్స అభ్యర్థించండి',
    'transport_title': 'రవాణా & కార్‌పూలింగ్',
    'transport_carpool_board': 'కార్‌పూల్ బోర్డ్',
    'transport_driver_requests': 'డ్రైవర్/రైడ్ అభ్యర్థనలు',
    'transport_post_ride': 'ఒక రైడ్‌ను పోస్ట్ చేయండి',
    'transport_post_request': 'అభ్యర్థనను పోస్ట్ చేయండి',
    'parking_title': 'పార్కింగ్ ఉల్లంఘనలు',
    'parking_report_violation': 'ఉల్లంఘనను నివేదించండి',
    'todays_dishes_title': 'ఈరోజు ఇంటి వంటకాలు',
    'post_todays_dish': 'ఈరోజు వంటకాన్ని పోస్ట్ చేయండి',
    'todays_dishes_subtitle': 'మీ పొరుగువారు తాజా చేసినవి, ఈ రోజు మాత్రమే!',
    'use_template': 'ఒక టెంప్లేట్‌ను ఉపయోగించండి',
    'dish_name': 'వంటకం పేరు',
    'price': 'ధర',
    'post_dish': 'వంటకాన్ని పోస్ట్ చేయండి',
    'latest_dishes': 'తాజా వంటకాలు',
    'auth_login': 'లాగిన్',
    'auth_logout': 'లాగ్ అవుట్',
    'auth_login_with_google': 'Googleతో సైన్ ఇన్ చేయండి',
    'auth_please_login': 'కొనసాగించడానికి దయచేసి లాగిన్ చేయండి',
    'profile_title': 'నా ప్రొఫైల్',
    'profile_setup_title': 'మీ ప్రొఫైల్‌ను పూర్తి చేయండి',
    'profile_setup_subtitle': 'దయచేసి అన్ని కమ్యూనిటీ లక్షణాలను యాక్సెస్ చేయడానికి మీ వివరాలను అందించండి.',
    'profile_name': 'మీ పేరు',
    'profile_block': 'బ్లాక్',
    'profile_flat_number': 'ఫ్లాట్ నంబర్',
    'profile_save': 'ప్రొఫైల్‌ను సేవ్ చేయండి',
    'profile_saved_success': 'ప్రొఫైల్ విజయవంతంగా సేవ్ చేయబడింది!',
  },
};